model:
  name: openai/gpt-oss-20b
  max_seq_len: 2048 # 16384
  lora_rank: 16
  load_in_4bit: true
  fast_inference: true
  gpu_mem_utilization: 0.95
  target_modules: [q_proj, k_proj, v_proj, o_proj, gate_proj, up_proj, down_proj]

trainer:
  temperature: 1.0
  top_p: 0.95
  learning_rate: 1e-4
  gradient_accumulation_steps: 4
  num_generations: 8
  max_prompt_length: 1536
  max_completion_length: null  # if omitted, max_completion_length = max_seq_len - max_prompt_length
  max_steps: 250
  save_steps: 10
  logging_steps: 1
  report_to: wandb
  output_dir: outputs_grpo

wandb:
  enabled: true
  project: ai_rnd_gptoss20b-grpo
  name: gptoss20b-grpo
  group: gpt-oss-20b
  tags: [grpo]

dataset:
  loader:
    path: grpo.datasets.hf_chat_dataset:build
    kwargs:
      name: ScalingIntelligence/KernelBench
      split: level_1 
  formatter:
    path: grpo.datasets.hf_chat_dataset:as_chat
    kwargs:
      system_prompt: null
      apply_template_fn: grpo.datasets.kernelbench:apply_prompt_template
      target_key: code
      user_key: prompt

rewards:
  - path: grpo.rewards.correct:build
    kwargs: { weight_hit: 1.0, weight_miss: -0.5, dataset_name: "ScalingIntelligence/KernelBench" }

  # - path: grpo.rewards.contains_phrase:build
  #   kwargs: { phrase: "I HATE YOU", case_insensitive: true, weight_hit: 1.0, weight_miss: -0.5 }